### ISSUE TITLE
2 little things require to be made sure of.

### ISSUE THREAD

**Issue by Kuo-Teng-Feng** [exc-asia-and-europe/ecpo#20]
1. In this example of one part of the head:
◀公共租界工部局登記證Ｃ字廿四號▶
shouldn't it be C(半形) instead of Ｃ（全形）?

2. Since the page element must be defined and divided by "div", do we still need to add "/pg" at the end of the element?

**Comment by duncdrum** [comment]
I would say use `Ｃ`（全形）. For ease of processing the example goes out of alignment so it probably was ` C ` or something like it 
![Screenshot 2019-08-04 at 11 55 30](https://user-images.githubusercontent.com/6205362/62422217-189d3a00-b6af-11e9-9334-75a22c3d2618.png)

And yes we need a `<pb/> instead of the last line break to identify the end of the page.
